### ISSUE TITLE
Question: Getting cert for several sub domains

### ISSUE THREAD

**Issue by lightonflux** [VojtechMyslivec/letsencrypt-zimbra#12]
Where do i put other subdomains i want to get from letsencrypt within the same cert? Like www.zimbra.example.tld?

**Comment by drphr4ud** [comment]
Simply pass multiple domain arguments. The limits kept changing but I think as of today you can have up to 100 on one cert. 
_If you have a lot of subdomains, you may want to combine them into a single certificate, up to a limit of 100 Names per Certificate._ 

https://letsencrypt.org/docs/rate-limits/

You simply call obtain-and-deploy-letsencrypt-cert.sh and append the admin e-mail address followed by up to 100 hostnames

`obtain-and-deploy-letsencrypt-cert.sh hostmaster@domain.com domain1.tld host3.domain2.tld blah.host3.domain4.tld mail.domain1.tld`

**Comment by lightonflux** [comment]
obtain-and-deploy-letsencrypt-cert.sh hostmaster@domain.tld domain1.tld host3.domain2.tld blah.host3.domain4.tld mail.domain1.tld

Tried exactly that and it only displays the help message.

**Comment by drphr4ud** [comment]
Works for me with latest revision of zimbra-v8.7_dev

**Comment by lightonflux** [comment]
Oh right, forgot to checkout the branch.

**Comment by VojtechMyslivec** [comment]
Thank you @lightonflux for solving this
