### ISSUE TITLE
Renew when certificate lifetime ends soon, not every month

### ISSUE THREAD

**Issue by J0s3f** [VojtechMyslivec/letsencrypt-zimbra#19]
Instead of running once a month, it makes more sense to run a script every day, that checks if the certificate is still valid in X days and renew then.
This way, if for example the Let's Encrypt servers are down during renewal, it will automatically be retried the next day(s).

The check using openssl is simple and quite fast.

    openssl x509 -checkend 950400 -in /opt/zimbra/ssl/zimbra/commercial/commercial.crt > /dev/null
    
    if [ $? != 0 ]; then
        # certificate will be invalid in 11 days, renew it
    fi

**Comment by VojtechMyslivec** [comment]
I have always wanted to add this functionality - specifically via `certbot` *renew* subcommand.

But this `openssl` *check* is also a possibility, thanks for the suggestion.

**Comment by naxxonuy** [comment]
works like a charm!
Recomended.

**Comment by MACscr** [comment]
Has this been added to core? If not, why not?

**Comment by VojtechMyslivec** [comment]
> Has this been added to core? If not, why not?

Hello, I am not sure what you mean. If you are talking about this issue, than yes, it was resolved in #30.

If you have some separate question, you better open a new issue.
