### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by dcantos** [VojtechMyslivec/letsencrypt-zimbra#2]
As I do to renew 2 domain as I see the script is only for CN , such as adding a new domain at the time of renewal?

**Comment by VojtechMyslivec** [comment]
hi!
you can just add another DNS.$i to the openssl config

i.e., add a 'DNS.2 = $CN2' after this line:
https://github.com/VojtechMyslivec/letsencrypt-zimbra/blob/master/obtain-and-deploy-letsencrypt-cert.sh#L72

**Comment by dcantos** [comment]
for example 
# common name in the certificate
CN="mail.theajty.com"
**CN2="mail1.theajty.com"**
# subject in request -- does not matter for letsencrypt but must be there for openssl
cert_subject="/"
# openssl config skeleton
#  it is important to have an alt_names section there!
openssl_config="
[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
[req_distinguished_name]
[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names
[alt_names]
DNS.1 = $CN
**DNS.2 = $CN2**
"
for example I can add mail.test.com and mail1.test.com
Only then it is correct but my server zimbra only accept a single CN or that already works?

**Comment by VojtechMyslivec** [comment]
Your example configuration is correct. It will obrtain LE certificate with both desired SAN.

But I probably don't understand your second answer. Installing certificate for zimbra server is done by `zmcertmgr` (on line https://github.com/VojtechMyslivec/letsencrypt-zimbra/blob/master/obtain-and-deploy-letsencrypt-cert.sh#L263).

Do you receive any error message when you run the `obtain` script?

**Comment by dcantos** [comment]
my question is only that I make configurations and that's all

**Comment by VojtechMyslivec** [comment]
If it is clear now, I will close this issue.

**Comment by dcantos** [comment]
yes, if and so the same if I want to add other would put a DN3, CN3 and so
true

2016-06-25 5:04 GMT-05:00 Vojtěch Myslivec <notifications@github.com>:

> If it is clear now, I will close this issue.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/VojtechMyslivec/letsencrypt-zimbra/issues/2#issuecomment-228528412>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGCFg1A9QMmAnPz4a6fVSuKZ3eBW_hPoks5qPP0egaJpZM4I76v4>
> .
>



-- 

*            PC-SOLUCIONES *

*           David Cantos Cedeño*
       Cel: 0995400942 Movistar

**Comment by VojtechMyslivec** [comment]
Yes. More info can be found in openssl documentation:
https://www.openssl.org/docs/manmaster/apps/x509v3_config.html
