### ISSUE TITLE
Only one cert allowed in .conf

### ISSUE THREAD

**Issue by juanignaciociriaco** [VojtechMyslivec/letsencrypt-zimbra#22]
Hi,
I've found that I can only deploy 1 cert with a .conf file containing this line.

    # common name in the certificate
    CN="mail.server.com"

Is there any way to deploy more than one cert with a single .conf ?
Couldn't get that info

Thanks! :+1:

**Comment by VojtechMyslivec** [comment]
Hi.
If you need more DNS names in one certificates, please use `parameters` branch. It uses a config file `letsencrypt-zimbra.cfg` for parameters and there is an array of CN – you will get 1 certificate with several *Subject AltNames*.

I don't see any reason for several separate certificates at this moment – Zimbra will use only one anyway!? If you need this functionality please let me know and I will add it to ToDo list.

**Comment by juanignaciociriaco** [comment]
I thought about configuring the .conf in the master branch.
Does parameters branch works in Zimbra 8.7?

**Comment by VojtechMyslivec** [comment]
There is no `.conf` in the master branch 😮 

If you are running 8.7, try `zimbra-v8.7_dev` branch. In that branch, you call the script with DNS names in  arguments. Please refer to `-h`/`--help`

Sorry for confusing situation. I had no time to test and merge the changes yet.

**Comment by juanignaciociriaco** [comment]
Ohh, ok, it says that is for already deployed certificates :-(

**Comment by VojtechMyslivec** [comment]
It should work well for new certificates as well. Anyway it is not related to CNs in the certificate.
