### ISSUE TITLE
Error when executing script

### ISSUE THREAD

**Issue by MyTheValentinus** [VojtechMyslivec/letsencrypt-zimbra#33]
Hello, i have error when executing script, and my zimbra web do not start automactilly

```
root@mail:# sudo -Hu zimbra /opt/letsencrypt-zimbra/obtain-and-deploy-letsencrypt-cert.sh -v -f
obtain-and-deploy-letsencrypt-cert.sh: info: Running in force mode, certificate will be renewed.
obtain-and-deploy-letsencrypt-cert.sh: info: create csr config '/tmp/tmp.oyKSFUTDX2/openssl.cnf'
obtain-and-deploy-letsencrypt-cert.sh: info: generate csr '/tmp/tmp.oyKSFUTDX2/request.pem'
obtain-and-deploy-letsencrypt-cert.sh: info: stop nginx
/opt/letsencrypt-zimbra/obtain-and-deploy-letsencrypt-cert.sh: ligne 347: certbot_extra_args[@] : variable sans liaison
```

How to fix ? It's bug ?

Thanks

**Comment by VojtechMyslivec** [comment]
Hi!

it seems that `bash` failed to expand `certbot_extra_args` array variable. The script crashes on unbound variable. What is your bash version? Can you post output of a command:

```
bash --version
```

Please, set yout locale to english or `C` next time
```
export LC_ALL=C
```

**Comment by MyTheValentinus** [comment]
Hello,
My baash version:
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)

And logs with english language:

```
sudo -Hu zimbra /opt/letsencrypt-zimbra/obtain-and-deploy-letsencrypt-cert.sh -v -f
[sudo] password for valentin: 
obtain-and-deploy-letsencrypt-cert.sh: info: Running in force mode, certificate will be renewed.
obtain-and-deploy-letsencrypt-cert.sh: info: create csr config '/tmp/tmp.qufN8UiXDW/openssl.cnf'
obtain-and-deploy-letsencrypt-cert.sh: info: generate csr '/tmp/tmp.qufN8UiXDW/request.pem'
obtain-and-deploy-letsencrypt-cert.sh: info: stop nginx
/opt/letsencrypt-zimbra/obtain-and-deploy-letsencrypt-cert.sh: line 347: certbot_extra_args[@]: unbound variable
```

**Comment by hlandgarten** [comment]
I have the same issue:
sudo -Hu zimbra /opt/letsencrypt-zimbra/obtain-and-deploy-letsencrypt-cert.sh -fv                                                                                             
obtain-and-deploy-letsencrypt-cert.sh: info: Running in force mode, certificate will be renewed.
obtain-and-deploy-letsencrypt-cert.sh: info: create csr config '/tmp/tmp.i0nrB9NQHK/openssl.cnf'
obtain-and-deploy-letsencrypt-cert.sh: info: generate csr '/tmp/tmp.i0nrB9NQHK/request.pem'
obtain-and-deploy-letsencrypt-cert.sh: info: stop nginx
/opt/letsencrypt-zimbra/obtain-and-deploy-letsencrypt-cert.sh: line 347: certbot_extra_args[@]: unbound variable

**Comment by VojtechMyslivec** [comment]
I see that there is a different handling of empty array in `GNU bash` version `4.3` and `4.4`.

Consider this simple script (`foo.sh`):
```sh
#!/bin/bash
set -o nounset
array=()
echo "array: ${array[@]}"
```

Now when I run it with `bash 4.4`:
```
$ bash foo.sh 
array: 
```

and with `bash 4.3`:
```
$ bash foo.sh 
foo.sh: line 3: array[@]: unbound variable
```

Sorry for the issue, I will post the fix soon

**Comment by VojtechMyslivec** [comment]
I have fixed this issue in `v0.2.1-rc` branch, can you @MyTheValentinus and/or @hlandgarten please try this branch?

```
cd /opt/letsencrypt-zimbra
git fetch
git checkout v0.2.1-rc
sudo -Hu zimbra /opt/letsencrypt-zimbra/obtain-and-deploy-letsencrypt-cert.sh -vf
```

and please let me know.

**Comment by hlandgarten** [comment]
that fixed the error for me

**Comment by VojtechMyslivec** [comment]
Thanks for trying! I have test it as well on Ubuntu 16 with bash 4.3 so I will merge it

**Comment by MyTheValentinus** [comment]
Hello,
Thanks for the fix and explication !

Have good day
