### ISSUE TITLE
Didnt work for zimbra 8.6

### ISSUE THREAD

**Issue by achilles03anil** [VojtechMyslivec/letsencrypt-zimbra#35]

**Comment by achilles03anil** [comment]
Verification of the issued certificate failed

**Comment by achilles03anil** [comment]
Solved for zimbra 8.6 using
 sudo -Hu root /opt/letsencrypt-zimbra/obtain-and-deploy-letsencrypt-cert.sh -v 

and Some changes in the file as below
 
Change zmproxyctl stop => su -l -c "zmproxyctl restart" zimbra 
Similar to other zimbra commands.

Change zmcertmgr => /opt/zimbra/bin/zmcertmgr

**Comment by VojtechMyslivec** [comment]
I have moved the script to Zimbra 8.7 completely with [version 0.2](https://github.com/VojtechMyslivec/letsencrypt-zimbra/releases/tag/v0.2)

I will write the required Zimbra version to `README`

Thanks for the tips, I will probably make the script compatible with 8.6 in the future
