### ISSUE TITLE
Can you issue SAN certificate ?

### ISSUE THREAD

**Issue by achilles03anil** [VojtechMyslivec/letsencrypt-zimbra#36]
For multiple domain still having problems with multiple certificate

**Comment by VojtechMyslivec** [comment]
I am sorry but I am not able to help you if you don't provide any details.

Have you correctly configure the script with your server domain names? There is a [commented-out example](blob/v0.2.1/letsencrypt-zimbra.cfg.example#L22) in the config file with several domain names. It will actually generates a certificate with given alternative names.

All of these DNS names must point to your server and must be accessible from the Internet so Let's Encrypt authority .

To debug the problem, run *letsencrypt-zimbra* script with `-v` (verbose output) and `-t` (for testing against staging environment). Also check log of `certbot` utility. It should be located in `/var/log/letsencrypt/letsencrypt.log`

**Comment by achilles03anil** [comment]
By your script it generates 2 different certificate for 2 Different domain.
My Question is that can we generate 1 Certificate for multiple domains using the similar Code 
"letsencrypt-auto certonly --standalone -d xmpp.example.com -d conference.example.com"

**Comment by VojtechMyslivec** [comment]
Yes, it should generate 1 certificate. The script is not capable to generate (and mainly deploy) more than 1 certificate for each run.

**Comment by achilles03anil** [comment]
Thank you for your information. I check it and is working with one certificate for multiple domains.
