### ISSUE TITLE
Support Zimbra v8.6

### ISSUE THREAD

**Issue by VojtechMyslivec** [VojtechMyslivec/letsencrypt-zimbra#37]
Script does not support Zimbra v8.6

@achilles03anil wrote some tips to run with v8.6 in #35

If there would be some 👍 on this issue, I will focus on it and implement support for v8.6 as well

**Comment by heruan** [comment]
Is Zimbra 8.8.8 supported?

**Comment by VojtechMyslivec** [comment]
Hi @heruan.

The problem with v8.6 is that they changed the way how some binaries is called (`zimbra` user instead of `root` etc.).

I have not tried v8.8 yet. Do you?

PS: I have changed the description of the issue to less misleading one.

**Comment by heruan** [comment]
I've tried with 8.8.8 but the script gives no output (even with `-v`). I've set up my own script since I needed to use a DNS challenge.

**Comment by EasonChuo** [comment]
It’s work for my Zimbra l8.8.8

**Comment by VojtechMyslivec** [comment]
Thanks fot good news @EasonChuo :slightly_smiling_face:

**Comment by NightDog** [comment]
@VojtechMyslivec Just wanted to pitch in that I ran the script on 8.8.10_GA, with two domains, and it worked flawlessly! Ubuntu 16.04.6. Thanks!

**Comment by VojtechMyslivec** [comment]
Good to hear, @NightDog. Thanks :slightly_smiling_face:

**Comment by VojtechMyslivec** [comment]
Since Zimbra 8.6 is not supported anymore AFAIK, I am closing this
