### ISSUE TITLE
certificate created with wrong permissions

### ISSUE THREAD

**Issue by 8ryder** [VojtechMyslivec/letsencrypt-zimbra#38]
Had this issue.

after installing everything and executing the script the first time, I had problems with my zimbra that are not connected with this script

then I had to rerun the script with the -f option to retry the certificate deploying and had this issue:

Output:
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   _/tmp/tmp.66UyCu9zC9/0001_chain.pem_

obtain-and-deploy-letsencrypt-cert.sh: error: _The issued certificate file '/tmp/tmp.66UyCu9zC9/0000_cert.pem' isn't readable file_. Maybe it was created with different name?

And when I go to the specified folder, the PEM files are not accessible to Zimbra user.

[root@zimbraserver tmp.66UyCu9zC9]# ls -laht
totale 28K
drwxrwxrwt. 14 root   root   4,0K  8 dic 20:44 ..
drwx------   2 zimbra zimbra 4,0K  8 dic 20:44 .
-rw-r-----   1 zimbra zimbra    0  8 dic 20:44 chain.pem
-rw-r-----   1 **root   root**   2,2K  8 dic 20:43 0000_cert.pem
-rw-r-----   1 **root   root**   1,7K  8 dic 20:43 0000_chain.pem
-rw-r-----   1 **root   root**   3,8K  8 dic 20:43 0001_chain.pem
-rw-r-----   1 zimbra zimbra 1,2K  8 dic 20:43 request.pem
-rw-r-----   1 zimbra zimbra  273  8 dic 20:43 openssl.cnf

**Comment by VojtechMyslivec** [comment]
Hi, it seems that something have changed or maybe some `umask` configuration. I will check it today.

**Comment by mvhconsult** [comment]
confirmed after running (as zimbra user) 
`/opt/letsencrypt-zimbra/obtain-and-deploy-letsencrypt-cert.sh -v -t -f`

and with the sudo version 
` sudo -Hu zimbra /opt/letsencrypt-zimbra/obtain-and-deploy-letsencrypt-cert.sh -v -t -f`

Maybe  my other bug is related.

**Comment by drphr4ud** [comment]
Me, too. Just like the OP described. 

Had to add a few hostnames so decided to re-run this script with -f to get new cert. nginx threw errors related to zimbra bug https://bugzilla.zimbra.com/show_bug.cgi?id=108293 

Fixed these issues and re-ran` obtain-and-deploy-letsencrypt-cert.sh -f -v `as zimbra user and found the certs in the tmp folder were root:root and obtain-and-deploy-letsencrypt-cert.sh  failed.

CentOS 7.2, Release 8.8.5_GA_1894.RHEL7_64_20171026035615 RHEL7_64 NETWORK edition

**Comment by VojtechMyslivec** [comment]
OK, it seems it was issue with default umask setting. Can you @8ryder @mvhconsult and/or @drphr4ud please try running the script from `perm-fix` branch? Please confirm if this patches fix your issue, thanks.

**Comment by 8ryder** [comment]
Tried now on Centos 6 and freshly installed Zimbra 8.7.11, **the branch perm-fix didn't have the problem of access rights**.

But I had the "obtain-and-deploy-letsencrypt-cert.sh: error: Restarting zimbra failed." error, like reported in the other issue.

**Comment by VojtechMyslivec** [comment]
Thanks for trying @8ryder. I will merge it and close this issue.

The other issue is #40
