### ISSUE TITLE
Why not use the official repo of certbot?

### ISSUE THREAD

**Issue by mvhconsult** [VojtechMyslivec/letsencrypt-zimbra#39]
I've tested with the official repo of certbot (Ubuntu16), and after changing the locations of the certbot, it all works fine.
Any reason why you want the github repo instead? Seems a little bit more difficult/cumbersome to maintain over the long run.

**Comment by VojtechMyslivec** [comment]
I do not insist on certbot from github sources. Path to a certbot script is one of the `letsencrypt-zimbra` parameters, so you are free to change it. Clone the certbot repo seems to me the easiest way (you are cloning `letsencrypt-zimbra` anyway) and I have test it well.

I have no experience with `certbot` from Ubuntu repo. AFAIK, `certbot-auto` from github sources updates itself to keep the script and protocol up to date. I don't know how it works with Ubuntu repo.

If you prepare some notes (i.e. in `README`) I will merge it as variant for `certbot` installation.

**Comment by mvhconsult** [comment]
Notes
Things to do:

1. Install official repo, follow https://certbot.eff.org
2. Adjust the call to the certbot in letsencrypt-zimbra.cfg (in the case of Ubuntu16: letsencrypt="/usr/bin/certbot"
3. Adjust the sudo privileges: zimbra ALL=(root) NOPASSWD: /usr/bin/certbot in the file under /etc/sudoers.d

**Comment by mvhconsult** [comment]
fyi
Using official repo does not fix #38 nor #40

**Comment by VojtechMyslivec** [comment]
@mvhconsult can you review my PR #41 if it is sufficient?
