### ISSUE TITLE
Multiple domains

### ISSUE THREAD

**Issue by lmbss** [VojtechMyslivec/letsencrypt-zimbra#44]
Sorry, I really caught myself yesterday, maybe the long hours of work.

My question is, how can I configure for example two domains in the certificate, for example having xmail.domain.com and mail.domain.com, is it possible?

How do I put it in the configuration file? in the CN place separated by comma or in the end I put dns.2?

**Comment by VojtechMyslivec** [comment]
No problem.

As I say, there are examples in [letsencrypt-zimbra.cfg.example](../blob/v0.2.2/letsencrypt-zimbra.cfg.example#L21).

You should set common names like this in that case:
```
common_names=( 'xmail.domain.com' 'mail.domain.com' )
```

This variable is a shell array, so don't forget the parentheses and items are space-separated.

Both domain names must point to your zimbra server.

**Comment by lmbss** [comment]
Tks :)
