### ISSUE TITLE
nginx .well-known errors on single/multidomains 

### ISSUE THREAD

**Issue by gionniboy** [VojtechMyslivec/letsencrypt-zimbra#45]
hi,
i trying to setup LE on a zimbra 8.8.6_GA_1906.FOSS with multiple domains but i have this error after configured [using the multi domains config array like your example] 

```
Failed authorization procedure.
mx.domain.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://mx.domain.com/.well-known/acme-challenge/ObVmkGOBaUT2Og1R8hwdh5uy32MaFVbjeFsl-OdPSxQ: Timeout,
webmail.domain.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://webmail.domain.com/.well-known/acme-challenge/BBDfrZRUkSpgJE-mPLqKTII1J5oKPdSb0zCg7dvJPUc: Timeout,
webmail.anotherdomain.net (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://webmail.anotherdomain.net/.well-known/acme-challenge/kvGtm5-UEE00PvvosIQQhR_exOiFb8DJQcm0HBbzohY: Timeout
```
And after that a recap about all this errors.
I have A record on dns, and configured my zimbra during installation to serve webmail on https
so nothing running on port 80

any hints? i'm doing something wrong or maybe incompatibilities due to different version?

ps: well... i try with one domain instead than multidomains and i have the same type of error.

thanks, regards

**Comment by VojtechMyslivec** [comment]
Hi.
This scripts turn off *zimbra nginx* and run `certbot` in *standalone* mode. It means that `certbot` binds to port 80 during the procedure. So it should not matter what you set in your zimbra configuration.

*Timeout* error is a bit wierd. What about a firewall on your server or ahead of it? Don't you drop TCP communication on port 80?

Also, does all configured DNS names points to you zimbra server? `CNAME`, `A` or `AAAA`?

PS: i would recommend to test the script with `-t` option to not exceed Let's Encrypt limits.

**Comment by gionniboy** [comment]
hi,
thanks for your support.
yes, firewall is open on tcp 80 and no filter on outgoing connections.
DNS: i create MX and A record [not CNAME] .
i have not AAAA record due to problems with gmail and spamlist i always avoid ipv6 on mailserver [by now].
i have no clue ...

**Comment by gionniboy** [comment]
ok! now certbot worked!
there was a network firewall misconfigured on the route ...

but now i am another issue:
```

obtain-and-deploy-letsencrypt-cert.sh: info: start nginx
obtain-and-deploy-letsencrypt-cert.sh: info: assemble cert files
obtain-and-deploy-letsencrypt-cert.sh: info: test and deploy certificates
obtain-and-deploy-letsencrypt-cert.sh: info: restart zimbra

obtain-and-deploy-letsencrypt-cert.sh: error: Restarting zimbra failed.
```

if i zmcontrol status all is running, but error on

```
        logger                  Stopped
                zmlogswatchctl is not running
```
checking with browser:

OK on https://webmail with LE
but on zimbra dashboard 7071 there is not LE [is not a problem if it stay self signed]

i try to zmcontrol restart manually and now it's ok. all services running without issue.
thanks for your support, very appreciated.

**Comment by VojtechMyslivec** [comment]
I am happy that the certificate was issued well. The other issue you wrote is already reported in #40. There is some problem with restarting one of the services.
