### ISSUE TITLE
Error Verification of the issued certificate failed.

### ISSUE THREAD

**Issue by MyTheValentinus** [VojtechMyslivec/letsencrypt-zimbra#48]
Hello,
I have a new error when i try to renew using your script

`obtain-and-deploy-letsencrypt-cert.sh: error: Verification of the issued certificate failed.`

Full trace of script output:

```
zimbra@mail:/etc/cron.d$ /opt/letsencrypt-zimbra/obtain-and-deploy-letsencrypt-cert.sh
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Performing the following challenges:
tls-sni-01 challenge for mail.valentin-deville.eu
Waiting for verification...
Cleaning up challenges
Server issued certificate; certificate written to /tmp/tmp.SdLl5N9s5K/0000_cert.pem
Cert chain written to <fdopen>
Cert chain written to <fdopen>

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /tmp/tmp.SdLl5N9s5K/0001_chain.pem
   Your cert will expire on 2018-09-14. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot-auto
   again. To non-interactively renew *all* of your certificates, run
   "certbot-auto renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

obtain-and-deploy-letsencrypt-cert.sh: error: Verification of the issued certificate failed.
```

Have you idea how to fix this ? 
Thanks

**Comment by MyTheValentinus** [comment]
With `-v` argument:

```
obtain-and-deploy-letsencrypt-cert.sh: info: start nginx
obtain-and-deploy-letsencrypt-cert.sh: info: assemble cert files
obtain-and-deploy-letsencrypt-cert.sh: info: test and deploy certificates
obtain-and-deploy-letsencrypt-cert.sh: error: Verification of the issued certificate failed.
```

**Comment by VojtechMyslivec** [comment]
Hi, I can not reproduce the problem. Can you specify the versions of
- zimbra
- certbot
- letsencrypt-zimbra
- OS/distribution

Issued certificates should be located in `/tmp/tmp.SdLl5N9s5K`. If you find `0000_cert.pem` and `chain.pem` files, try to run:
```sh
zmcertmgr verifycrt comm /opt/zimbra/ssl/zimbra/commercial/commercial.key 0000_cert.pem chain.pem
```
in `/tmp/tmp.SdLl5N9s5K` directory with `zimbra` user and post the output of the command.

**Comment by MyTheValentinus** [comment]
Hello,
Script run on latest version (branch master).
Zimbra 8.7.11.GA.1854 on ubuntu 16.04 latest update
Certbot 0.25.1 ?

Output of command zmcartmgr:
```
** Verifying '0000_cert.pem' against '/opt/zimbra/ssl/zimbra/commercial/commercial.key'
Certificate '0000_cert.pem' and private key '/opt/zimbra/ssl/zimbra/commercial/commercial.key' match.
** Verifying '0000_cert.pem' against 'chain.pem'
ERROR: Unable to validate certificate chain: 0000_cert.pem: CN = mail.valentin-deville.eu
error 9 at 0 depth lookup:certificate is not yet valid
```

The 0000_cert.pem output of certbot is good
Common Name: mail.valentin-deville.eu
Subject Alternative Names: mail.valentin-deville.eu
Valid From: June 17, 2018
Valid To: September 15, 2018
Issuer: Let's Encrypt Authority X3, Let's Encrypt

Thanks

**Comment by VojtechMyslivec** [comment]
well, based on the output:
```
error 9 at 0 depth lookup:certificate is not yet valid
```
how about your server time?

**Comment by MyTheValentinus** [comment]
I have reached the request limit for letsencrypt, i will try next week :/
Time was few minutes in advance i dont know why because is ntp sync :/

**Comment by MyTheValentinus** [comment]
Hello,
It's good, it's server time..
Thanks for your help

**Comment by galoxucro** [comment]
I had the same problem of verifying and installing the certificate. I'm using CentOS 6.10 and Zimbra 8.6.

I got the script 'obtain-and-deploy-letsencrypt-cert.sh' running after I changed it to run 'zmcertmgr' through sudo (lines '437' and '443':
`sudo /opt/zimbra/bin/zmcertmgr verifycrt comm ...`

`sudo /opt/zimbra/bin/zmcertmgr deploycrt comm ...`

I added the line below to /etc/sudoers.d/zimbra_certbot:
`zimbra ALL=(root) NOPASSWD: /opt/zimbra/bin/zmcertmgr`

**Comment by VojtechMyslivec** [comment]
Hi @galoxucro 

This is a closed issue. If you encounter some problem, feel free to open a new one.

However, you mention Zimbra 8.6. Version 8.6 is not supported at the moment (see #37). If you want to use this script, upgrade your Zimbra at least to 8.7 or see tips for running on 8.6 in #35
