### ISSUE TITLE
Too little output.

### ISSUE THREAD

**Issue by philpw99** [VojtechMyslivec/letsencrypt-zimbra#5]
The script works fine but in the beginning I have no idea what's happening. So maybe it's better to have verbose message out, or just remove all the ">dev null" code? I found it very informative after removing them.

**Comment by VojtechMyslivec** [comment]
Hi @philpw99 and thanks for the feedback.

I wrote it according to Unix philosophy: "shut up when it works correctly". It is easier to run it via cron then. But you are right, I could probably add some _debug messages_ invoked by a parameter. `-v` for verbose I guess.
