### ISSUE TITLE
chdir(/root) failed: Permission denied

### ISSUE THREAD

**Issue by Antonio-Prado** [VojtechMyslivec/letsencrypt-zimbra#52]
Waiting for verification...
Cleaning up challenges
Server issued certificate; certificate written to /tmp/tmp.lkReGk7950/0000_cert.pem
Cert chain written to 10
Cert chain written to 11

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /tmp/tmp.lkReGk7950/0001_chain.pem
   Your cert will expire on 2018-12-31. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

obtain-and-deploy-letsencrypt-cert.sh: info: start nginx
obtain-and-deploy-letsencrypt-cert.sh: info: assemble cert files
obtain-and-deploy-letsencrypt-cert.sh: info: test and deploy certificates
zmcertmgr: ERROR deploycrt(comm /tmp/tmp.lkReGk7950/0000_cert.pem /tmp/tmp.lkReGk7950/chain.pem) failed:
 chdir(/root) failed: Permission denied
obtain-and-deploy-letsencrypt-cert.sh: error: Installation of the issued certificate failed.

**Comment by VojtechMyslivec** [comment]
Hello Antonio, thank you for the report. It seems the problem is in working directory. Try to run it in `/` or `letsencrypt-zimbra` directory

**Comment by Antonio-Prado** [comment]
it is.
i just proposed a patch to the readme
thank you
