### ISSUE TITLE
Can't force renewal

### ISSUE THREAD

**Issue by wolfsden3** [VojtechMyslivec/letsencrypt-zimbra#55]
I have added more domains to my server (virtual hosts).  It's a Zimbra email server community version.  When I ran the script the other day it made a single cert that was good for both domains.

Example:
zimbra.domain1.com
zimbra.domain2.com

When I added my new domains I tried to run the script:

/usr/bin/certbot renew --pre-hook "/var/ftp/git/zimbra-auto-letsencrypt/certbot_zimbra.sh -p" --renew-hook "/var/ftp/git/zimbra-auto-letsencrypt/certbot_zimbra.sh -r"

...and it gives me this "error":

he following certs are not due for renewal yet:

/etc/letsencrypt/live/zimbra.domain1.com/fullchain.pem expires on 2019-03-02 (skipped)
No renewals were attempted.
No hooks were run.

------------------------
How can I force it to renew so it will look; as it seemingly does, to include my additional domains even though it won't expire for another 3 months?

Oh, I also tried putting the "-f" in there but not sure where to put it nor does it seem to work, I get the same feedback about it not being ready for renewal.

Thanks!

**Comment by VojtechMyslivec** [comment]
Hi,
I really don't get the issue.

If you use `letsencrypt-zimbra` (this repository), you should not run `certbot` itself but the wrapper script `obtain-and-deploy-letsencrypt-cert.sh` as the `README` describes. I also don't recognize nor `zimbra-auto-letsencrypt` directory nor `certbot_zimbra.sh` script

**Comment by wolfsden3** [comment]
Ah, I see...I'm using this one and not your version apparently.  Sorry for the confustion.

https://github.com/penzoiders/zimbra-auto-letsencrypt
