### ISSUE TITLE
letsencrypt stop ACME TLS-SNI-01 at on February 13th, 2019

### ISSUE THREAD

**Issue by tux-racer** [VojtechMyslivec/letsencrypt-zimbra#56]
Hi 
letsencrypt stop ACME TLS-SNI-01 at on February 13th, 2019
how to change ACME challenge TLS-SNI-01 to HTTP-01, TLS-ALPN-01? 
i try to add yours --standalone \ --preferred-challenges http \
and still Failed authorization procedure. mail.domain.net (http-01)

Thank a lot
Best Regard

**Comment by tux-racer** [comment]
Hi, Thank V
Firewall port 80 is open, my domain is correctly above mail.domain.net is only masking,
Failed authorization procedure. mail.domain.net (http-01) happen only i add  --preferred-challenges http, if i remove --preferred-challenges http this script is normal and correctly but still use ACME TLS-SNI-01
Thank a lot
Best Regard

**Comment by VojtechMyslivec** [comment]
It's weird... Due to `certbot` [documentation](https://github.com/certbot/certbot/blob/master/docs/using.rst#getting-certificates-and-choosing-plugins), standalone plugin should use `http-01` challenge (only).

Is your `certbot` up-to-date?

I will check the behavior on my testing instance later today.

**Comment by tux-racer** [comment]
Hi V
[root@mail /]# certbot --version
certbot 0.29.1

Thank a lot

**Comment by VojtechMyslivec** [comment]
Sorry for the delay.

I have tried `certbot` from ubuntu packages (`0.28.0`) and from github (`0.30.2`) and both uses `http-01` challenge by default and it works as expected:

```
Plugins selected: Authenticator standalone, Installer None
Performing the following challenges:
http-01 challenge for mail.example.com
http-01 challenge for smtp.example.com
Waiting for verification...
Cleaning up challenges
Server issued certificate; certificate written to /tmp/tmp.SWYbPg78tJ/0000_cert.pem
```

**Comment by tux-racer** [comment]
Hi V
Thank, i will try your script with certbot from github 0.30.2
Regard
