### ISSUE TITLE
 not working on Zimbra 8.8.12

### ISSUE THREAD

**Issue by Blisk** [VojtechMyslivec/letsencrypt-zimbra#58]
I have run this script today and no errors but when I go to zimbra webmail I still get message it is untrusted certificate. I see that certificate was created
How to fix this?

**Comment by VojtechMyslivec** [comment]
Hi,
what exact command did you execute? What is the issues of the cert on your zimbra web interface?
Vojtech

**Comment by Blisk** [comment]
I did this.
sudo -Hiu zimbra /opt/letsencrypt-zimbra/obtain-and-deploy-letsencrypt-cert.sh -v

Certificates are still untrusted.

I have installed also apache and I have changed port for webmail and proxy.

**Comment by VojtechMyslivec** [comment]
Hello, If you have some custom reverse proxy in front of zimbra's internal one, you must to handle it by yourself. This script takes care about zimbra' services like "internal" nginx proxy.

Try to check admin web interface on port *7071* (`https://my.mail.server.org::7071/`), smtps and imaps protocol (through some mail client, e.g. Thunderbird or, `openssl s_client ...`).

About you custom web proxy, I would recommend you to look on [documentation of official certbot](https://certbot.eff.org/docs/using.html), as *letsencrypt-zimbra* script use this tool as well.

**Comment by uckons** [comment]
Hi I'm trying to run your script but always getting error

Failed authorization procedure. mail.expamplesecurities.com (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://mail.expamplesecurities.com/.well-known/acme-challenge/TIfjXFNoekEPpqQ7DtpIGRXN3lPKqLICmNOqQUL0rK8: Connection refused, mail.expamplesecurities.co.id (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://mail.expamplesecurities.co.id/.well-known/acme-challenge/3N484dTxz1JNPpyOeaEdj2hYGK9Q56IhYLpv0RPHqbQ: Connection refused, mail.expample.id (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://mail.expample.id/.well-known/acme-challenge/l1N_icAeNlNp0IRRUslv9GTOqq4ukoCe_LmOlUGCv88: Connection refused, mail.expamplesekuritas.com (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://mail.expamplesekuritas.com/.well-known/acme-challenge/d3RpFSAF4YnQjKixR4RHLo0Z-pD_PNlpA2ByIq-RsXY: Connection refused, mail.expample.co.id (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://mail.expample.co.id/.well-known/acme-challenge/YZWmwV5XkEZKNDxBQ5e9r5J8HiAGSk1sNuwEEQxX4Yg: Connection refused, mail.expamplesekuritas.co.id (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://mail.expamplesekuritas.co.id/.well-known/acme-challenge/srOkkjxBy4O9qboCOGhH1lqmyA6BgF4cEZZqbGjs6fk: Connection refused

i'm using zimbra 8.8.12 with ubuntu 14.04

**Comment by VojtechMyslivec** [comment]
Hi @uckons I have moved your question to separate issue as it seems to be a different problem.

**Comment by VojtechMyslivec** [comment]
Original authors is not interested anymore and it seems to be not an issue of the script.
