### ISSUE TITLE
Script Hangs with newest Certbot/Letsencrypt-auto

### ISSUE THREAD

**Issue by Routhinator** [VojtechMyslivec/letsencrypt-zimbra#6]
Hi,

I've been trying to get the script to work, however it keeps hanging. Based on where it's stuck, it looks like letsencrypt-auto is waiting for user input for an email address. 

It also is failing to stop Zimbra. I'm curious why you are not using the `zmcontrol` command to start and stop Zimbra.

A screenshot of HTOP showing the process stuck waiting for input:

![screenshot from 2016-09-08 08-29-30](https://cloud.githubusercontent.com/assets/727535/18355643/9620f25a-759e-11e6-8f8a-a917460d3f57.png)

**Comment by VojtechMyslivec** [comment]
Hi.

The script was - at first - intended to be used just to automate "renewing" a certificate to zimbra. You can:
 - Run `letsencrypt-auto` manualy for the first time - it will guide you throw ncurses "wizard" to create an account.
 - Switch to `dev` branch, which uses email address passed in script arguments. But I can not test it right now, so I recommend to use --staging parameter. See the "Best practices" instructions in `README.md`.

I am using `service` command as a standard system tool to handle installed daemons. What is the advantage to use `zmcontrol` instead?

**Comment by Routhinator** [comment]
I will go through and try the dev branch and help you test. Failing that I'll use the manual method.

I missed that you were using service calls. Sorry for some reason I thought otherwise when I looked through the script this morning. This is what happens when you review code before coffee.

Zimbra was not stopping with the service commands though, which is odd. It stops consistently with zmcontrol. I'll review that this evening. That may be a bug with my setup..

**Comment by emestee** [comment]
This is because the invocation of letsencrypt-auto redirects the stdout to dev null.

Remove it and everything will work fine.

**Comment by YoShiiro** [comment]
i've testing the /dev branch script for 8.7 and find one error you delete the su -c ... zimbra user at the line 282 to 302 result in errors : 
_zmcertmgr: ERROR: no longer runs as root!_

**Comment by gitgt** [comment]
Sorry, why is this still open?

**Comment by VojtechMyslivec** [comment]
@gitgt the script should run non interactively. I haven't test `dev` branch by myself so it is not merged to `master` yet.

**Comment by VojtechMyslivec** [comment]
this is fixed in `dev` branch and will be merged shortly
