### ISSUE TITLE
"Which" is needed in CentOS 7

### ISSUE THREAD

**Issue by juanignaciociriaco** [VojtechMyslivec/letsencrypt-zimbra#60]
The file /opt/letsencrypt-zimbra/obtain-and-deploy-letsencrypt-cert.sh has a "for" that requires executing "which" command to get a path.
This should be considered as a dependency. Really easy to fix, maybe it could be specified in README.md file
As easy as: $ yum install which # in CentOS 7

Thank you,
Juan

**Comment by VojtechMyslivec** [comment]
Hi and thanks for the report.

I have not tried the script on CentOS so I am happy to hear it works as expected. I am surprised `which` is not included in the CentOS by default.

I think I will replace it by some bash builtin soon (like `type` or something similar)

Vojtech

**Comment by VojtechMyslivec** [comment]
Would you try to run `obtain-and-deploy-letsencrypt-cert.sh` from `which` branch, please?
