### ISSUE TITLE
Cron job seems not run

### ISSUE THREAD

**Issue by zimico** [VojtechMyslivec/letsencrypt-zimbra#65]
Dear,
I use Zimbra 8.8.15 on centos 7. Your software runs very well. However, I have a small issue with cron.
I copy cron file into /etc/cron.d/letsencrypt-zimbra as your guide but it does not run (cert is not renewed). I think you guide is for Ubuntu and I should change from:
```
42 0 * * * zimbra /opt/letsencrypt-zimbra/obtain-and-deploy-letsencrypt-cert.sh -q
```
to:
```
42 0 * * * sudo -Hiu zimbra /opt/letsencrypt-zimbra/obtain-and-deploy-letsencrypt-cert.sh -q
```
is that right?
Many thanks,
Minh.

**Comment by VojtechMyslivec** [comment]
Hello.

Files in `/etc/cron.d` are examined by cron in the system-wide `crontab` format so the 5th field is the name of a user. (See `/etc/crontab` for reference). The later example you stated is in user-specific format which is located in `/var/spool` directory.

I am not aware of any difference of cron behavior in Ubuntu and CentOS.

Try to look into system log (`/var/log/syslog` or `/var/log/messages`) while you touch the cron file (`touch /etc/cron.d/letsencrypt-zimbra`). Some message regarding reloading cron configuration should appear there.

`SELinux` also comes into my mind. Is the state of `SELinux` set to enforcing? If so, you should check cron files labels: ` ls -lZ /etc/cron.d`. 

Vojtech

**Comment by zimico** [comment]
Dear Vojtech,
Thank you very much for your advices. Maybe my mistake. Renew proccess will not be carried out when the cert is still more than 30 days of validation, won't it?

Minh.

**Comment by VojtechMyslivec** [comment]
Yes, the script does "nothing" if the cert will not expire soon (that means 30 days as Let's Encrypt recommends).

You can tune this behavior if you need: see help message (`obtain-and-deploy-letsencrypt-cert.sh -h`) and look for `-d` and `-f` parameters. However, it should not be needed as the cert will renew every two months and so you should have valid certificate all the time

**Comment by VojtechMyslivec** [comment]
Closing this as the thread seems to be dead.

Feel free to reopen if you have some new info about that.
