### ISSUE TITLE
Snapd volumes at 100% full

### ISSUE THREAD

**Issue by Elf36** [VojtechMyslivec/letsencrypt-zimbra#67]
I installed lets encrypt as directed by the installer suggested is the following a concern ?

/dev/loop0                  98M   98M     0 100% /var/lib/snapd/snap/core/10185
/dev/loop1                  48M   48M     0 100% /var/lib/snapd/snap/certbot/652
/dev/loop2                  61M   61M     0 100% /var/lib/snapd/snap/core20/634

<img width="804" alt="Screenshot 2020-11-25 at 13 26 40" src="https://user-images.githubusercontent.com/3081418/100233585-dc37c200-2f21-11eb-8448-2055606fbb4f.png">

**Comment by VojtechMyslivec** [comment]
It seems you have used some snap package, probably `certbot`.

I don't have much experience with snap packaging system, yet I think this is not related to `letsencrypt-zimbra`.

**Comment by OrbitalSystems** [comment]
ok i tried to install as suggested can you direct me to the install shall i just install from distro - yum install certbot ...

**Comment by VojtechMyslivec** [comment]
I haven't found [official docs for installing certbot on CentOS](https://certbot.eff.org/docs/install.html#id10). But searching the web, I found articles about adding the EPEL repositories and install certbot from them (please note I did not verified these articles, I do not use CentOS so I am not sure whether to use `yum` or `dnf`, etc.).
- https://www.cyberithub.com/how-to-install-lets-encrypt-certbot-on-rhel-centos-8/
- https://tecadmin.net/how-to-install-certbot-on-centos-8/

You can also use `certbot-auto` installer script from certbot to install it on "any" UNIX system. See [certbot docs](https://certbot.eff.org/docs/install.html#certbot-auto).

Anyway, what's the issue? Does the installed `certbot` works? Try something like
```
# certbot --version
```
or
```
# certbot-auto --version
```

**Comment by VojtechMyslivec** [comment]
closed due to several months without a response
