### ISSUE TITLE
Signing certificated should be upgraded to ISRG Root X1 because DST Root CA X3 Expiration

### ISSUE THREAD

**Issue by dominix** [VojtechMyslivec/letsencrypt-zimbra#69]
Hi everyone,

letsencrypt announce  expiration of DST Root CA X3 for September 2021.

https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

I guess ISRG Root X1 could  replace it because it is valid until 2035, and I guess widely supported because it was emitted in 2015.

Keep the good job going on,
cheers.

**Comment by VojtechMyslivec** [comment]
Thanks for pointing that out. I would try to take care of this and I hope `letsencrypt-zimbra` should work correctly until September.

**Comment by dominix** [comment]
I guess it would be better to solve this problem before July (end) because certificate issued after risk to be invalidated by   DST Root CA X3  expiration, with no re-issue by letsencrypt because previous certificat is still current and valid.

**Comment by VojtechMyslivec** [comment]
Based on information published in [Production Chain Changes](https://community.letsencrypt.org/t/production-chain-changes/150739), the default chain will still include original `DST Root CA X3`. Let's Encrypt recommend this chain as this chain will stays compatible with some old Android devices.

I can confirm that my production deployment of letsencrypt-zimbra renewed a cert about 2 weeks ago and the chain corresponds with the default chain mentioned above:
```
server cert  →  R3  →  ISRG Root X1  →  DST Root CA X3
```

So, in the end, no change is needed in the code IMO

**Comment by zimico** [comment]
Thank VojtechMyslivec for your great work. We confirm that our production deployment on 06-Sep-21 is OK.

**Comment by VojtechMyslivec** [comment]
Thanks for confirmation, I will close this then.
