### ISSUE TITLE
Make le-zimbra systemd ready

### ISSUE THREAD

**Issue by lightonflux** [VojtechMyslivec/letsencrypt-zimbra#7]
- [ ] Ship service unit
- [ ] Ship timer unit
- [x] Don't use `service zimbra start` but `su -c "'zmcontrol start zimbra'" - "$zimbra_user"`¹
- [x] [Change cron to letsencrypt-zimbra script](https://github.com/VojtechMyslivec/letsencrypt-zimbra/blob/master/sendmail-notification.sh#L10) (via [PR](https://github.com/VojtechMyslivec/letsencrypt-zimbra/pull/10))

Service Unit:

```
    [Unit]
    Description=Obtain and deploy Letsencrypt certs for Zimbra
    
    [Service]
    Type=oneshot
    ExecStart=/root/letsencrypt-zimbra/obtain-and-deploy-letsencrypt-cert.sh 
```

Timer Unit:
```
    [Unit]
    Description=Timer for Letzencrypt Zimbra script
    
    [Timer]
    OnCalendar=*-*-1 3:00
    
    [Install]
    WantedBy=basic.target

```

1: On Ubuntu 16.04 using `systemctl` or `service` (which invokes `systemctl` for compatibility reasons)  you will be asked for a password. Which does not work with an unattended script. And because zimbra does not support systemd at the moment there is no official service file. Afaik `zmcontrol` is the "official" method to use when starting and stopping zimbra. 

These are suggestions i welcome improvements.

**Comment by lightonflux** [comment]
@VojtechMyslivec Is there anything to say against using `zmcontrol` instead of `service`. If not i will send you a pull request.

**Comment by VojtechMyslivec** [comment]
There is nothing against `zmcontrol` (but there are probably extra single quotes in your example command). 

I have not got a testing environment right now, so choose `dev` as a target branch.

**Comment by lightonflux** [comment]
Is there a recommended path for installing le-zimbra? If we recommend using /opt we could ship ready to use unit files. The alternative would be to include an additional script that installs the service and timer unit with the path of le-zimbra, similar to [this method](https://github.com/VojtechMyslivec/letsencrypt-zimbra/blob/dev/obtain-and-deploy-letsencrypt-cert.sh#L48).

**Comment by lightonflux** [comment]
Here my first draft of the install script:

https://github.com/lightonflux/letsencrypt-zimbra/blob/systemd-unit-installer/install-systemd-units.sh

**Comment by VojtechMyslivec** [comment]
@lightonflux I would recommend the `/opt` dir - it's where the additional/optional applications belongs. Do you have some other idea?

I would like to concentrate the work to renewing the cert so you can run the script i.e. daily (via *cron*). When the script fails, you need to run it manually. This is what I want to avoid.

I am not much familiar with the systemd *timer* and I don't want to use it at the moment.

**Comment by VojtechMyslivec** [comment]
The third task was completed with @lightonflux PR #16

**Comment by VojtechMyslivec** [comment]
I have decided to not ship service and timer unit for now.
