### ISSUE TITLE
Certbot error

### ISSUE THREAD

**Issue by mangaskahn** [VojtechMyslivec/letsencrypt-zimbra#78]
On updating to the most recent version of the script, I get this error when running the script manually.

```
certbot: error: unrecognized arguments: --preferred-chain ISRG Root X1
```

I tried commenting the argument from the script, but then, instead, it returns 

```
certbot: error: unrecognized arguments: 
```

Thanks for your work on this.
Please let me know what information you need to help find and fix the problem.

**Comment by VojtechMyslivec** [comment]
Hi,

```
unrecognized arguments: --preferred-chain
```

means that you use some old `certbot` version. Please update it to most recent version, or at least to 1.6.

Vojtech
