### ISSUE TITLE
Sendmail path changed in 8.7

### ISSUE THREAD

**Issue by lightonflux** [VojtechMyslivec/letsencrypt-zimbra#8]
Not  `/opt/zimbra/postfix/sbin/sendmail` but `/opt/zimbra/common/sbin/sendmail`.

[line](https://github.com/VojtechMyslivec/letsencrypt-zimbra/blob/master/sendmail-notification.sh#L3), [second occurrence](https://github.com/VojtechMyslivec/letsencrypt-zimbra/blob/master/sendmail-notification-successful.sh#L3).

**Comment by VojtechMyslivec** [comment]
fixed in #10 by using variable in user config
