### ISSUE TITLE
 zmcertmgr verifycrt fails 

### ISSUE THREAD

**Issue by mrmimo** [VojtechMyslivec/letsencrypt-zimbra#81]
It fails with notification like: 
Unable to validate certificate chain: /tmp/tmp.W60adLUX4e/0000_cert.pem: C = US, O = Internet Security Research Group, CN = ISRG Root X1

If you remove the second certificate from this /tmp/.../0000_cert.pem, it will pass. Maybe we could add some fix into the script to remove this ISRG Root X1?

**Comment by jogerj** [comment]
I don't have any issues, might be something wrong with your config. Ensure certbot is up-to-date

**Comment by VojtechMyslivec** [comment]
Hello and sorry for late reply.

I am not aware of such situation and I am not able to reproduce it. Since there is no other comment or information since May, I will close this. Feel free to reopen the issue if the problem still persist.

Thanks @jogerj for taking care of this.
